Client.create! email: 'client@example.com',
               password: 'password',
               name: 'João da Silva',
               cpf: '28142464020'

buffet_owners = [
  { email: 'owner1@example.com', password: 'password1' },
  { email: 'owner2@example.com', password: 'password2' },
  { email: 'owner3@example.com', password: 'password3' },
  { email: 'owner4@example.com', password: 'password4' },
  { email: 'owner5@example.com', password: 'password5' }]

buffets = [
  { brand_name: 'Buffet da Maria',
    corporate_name: 'Maria Ltda',
    cnpj: '51995596000148',
    phone: '11987654321',
    address: 'Rua das Flores',
    district: 'Centro',
    city: 'São Paulo',
    state: 'SP',
    cep: '02478150',
    description: 'Buffet especializado em festas infantis.',
    buffet_owner_id: 1 },

  { brand_name: 'Buffet do João',
    corporate_name: 'João Buffet',
    cnpj: '74896924000154',
    phone: '11976543210',
    address: 'Avenida Principal',
    district: 'Bairro Novo',
    city: 'Rio de Janeiro',
    state: 'RJ',
    cep: '77829146',
    description: 'Buffet completo para casamentos e eventos corporativos.',
    buffet_owner_id: 2 },

  { brand_name: 'Buffet Encantado',
    corporate_name: 'Encantado Festas',
    cnpj: '94500187000136',
    phone: '1133333333',
    address: 'Rua das Estrelas',
    district: 'Jardim Primavera',
    city: 'Curitiba',
    state: 'PR',
    cep: '69306398',
    description: 'O lugar perfeito para festas temáticas e eventos sociais.',
    buffet_owner_id: 3 },

  { brand_name: 'Buffet Sabores do Brasil',
    corporate_name: 'Sabores do Brasil Ltda',
    cnpj: '00255206000162',
    phone: '1144444444',
    address: 'Avenida Central',
    district: 'Centro',
    city: 'Brasília',
    state: 'DF',
    cep: '69314142',
    description: 'Buffet especializado em culinária brasileira para eventos corporativos.',
    buffet_owner_id: 4 },

  { brand_name: 'Buffet do Carlos',
    corporate_name: 'Carlos & Cia',
    cnpj: '21132671000186',
    phone: '1132323232',
    address: 'Praça das Árvores',
    district: 'Vila Verde',
    city: 'Porto Alegre',
    state: 'RS',
    cep: '41253244',
    description: 'Buffet com cardápio variado para todos os tipos de eventos.',
    buffet_owner_id: 5 }]

event_types = [
  { name: 'Casamento',
    description: 'Celebração do amor entre duas pessoas.',
    minimum_attendees: 50,
    maximum_attendees: 200,
    duration: 120,
    menu: 'Buffet completo com opções de carne, peixe e vegetariano.',
    provides_alcohol_drinks: 1,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 1 },

  { name: 'Aniversário Infantil',
    description: 'Festa para celebrar o aniversário de uma criança.',
    minimum_attendees: 20,
    maximum_attendees: 50,
    duration: 80,
    menu: 'Cardápio infantil com salgadinhos, doces e bolo decorado.',
    provides_alcohol_drinks: 0,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 2 },

  { name: 'Evento Corporativo',
    description: 'Encontro de empresas para networking ou celebrações.',
    minimum_attendees: 30,
    maximum_attendees: 300,
    duration: 160,
    menu: 'Opções variadas de canapés, finger foods e bebidas.',
    provides_alcohol_drinks: 1,
    provides_decoration: 0,
    provides_parking_service: 1,
    serves_external_address: 1,
    buffet_id: 3 },

  { name: 'Chá de Bebê',
    description: 'Celebração do próximo bebê que está para chegar.',
    minimum_attendees: 10,
    maximum_attendees: 50,
    duration: 60,
    menu: 'Salgadinhos, bolos e doces diversos.',
    provides_alcohol_drinks: 0,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 4 },

  { name: 'Formatura',
    description: 'Celebração da conclusão de um curso ou etapa acadêmica.',
    minimum_attendees: 50,
    maximum_attendees: 200,
    duration: 100,
    menu: 'Buffet com opções de jantar e finger foods.',
    provides_alcohol_drinks: 1,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 5 },

  { name: 'Festa de Noivado',
    description: 'Celebração do compromisso de casamento.',
    minimum_attendees: 30,
    maximum_attendees: 100,
    duration: 80,
    menu: 'Canapés, bebidas e bolo comemorativo.',
    provides_alcohol_drinks: 1,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 1 },

  { name: 'Festa de Natal',
    description: 'Celebração do Natal com amigos e familiares.',
    minimum_attendees: 20,
    maximum_attendees: 150,
    duration: 120,
    menu: 'Ceia natalina com peru, tender, e acompanhamentos típicos.',
    provides_alcohol_drinks: 1,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 2 },

  { name: 'Evento Cultural',
    description: 'Evento para promover a cultura, arte e entretenimento.',
    minimum_attendees: 50,
    maximum_attendees: 500,
    duration: 200,
    menu: 'Lanches, petiscos e bebidas variadas.',
    provides_alcohol_drinks: 0,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 1,
    buffet_id: 3 },

  { name: 'Festa de Reveillon',
    description: 'Celebração do Ano Novo com fogos de artifício e festividades.',
    minimum_attendees: 50,
    maximum_attendees: 300,
    duration: 160,
    menu: 'Buffet completo com pratos especiais para a virada do ano.',
    provides_alcohol_drinks: 1,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 4 },

  { name: 'Festa Junina',
    description: 'Celebrando as tradições juninas com comidas típicas e danças.',
    minimum_attendees: 30,
    maximum_attendees: 200,
    duration: 100,
    menu: 'Barracas com comidas típicas como milho verde, canjica, e quentão.',
    provides_alcohol_drinks: 0,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 5 },

  { name: 'Conferência',
    description: 'Evento de grande porte com palestras e workshops.',
    minimum_attendees: 100,
    maximum_attendees: 1000,
    duration: 240,
    menu: 'Coffee breaks, almoços e jantares.',
    provides_alcohol_drinks: 0,
    provides_decoration: 0,
    provides_parking_service: 1,
    serves_external_address: 1,
    buffet_id: 1 },

  { name: 'Festa Temática',
    description: 'Celebração com tema específico, como anos 80 ou tropical.',
    minimum_attendees: 20,
    maximum_attendees: 100,
    duration: 80,
    menu: 'Comida e bebida relacionadas ao tema da festa.',
    provides_alcohol_drinks: 1,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 2 },

  { name: 'Desfile de Moda',
    description: 'Apresentação das últimas tendências de moda.',
    minimum_attendees: 50,
    maximum_attendees: 500,
    duration: 120,
    menu: 'Petiscos e drinks especiais para os convidados.',
    provides_alcohol_drinks: 1,
    provides_decoration: 0,
    provides_parking_service: 1,
    serves_external_address: 1,
    buffet_id: 3 },

  { name: 'Concerto',
    description: 'Apresentação musical ao vivo.',
    minimum_attendees: 50,
    maximum_attendees: 500,
    duration: 80,
    menu: 'Petiscos e bebidas durante o intervalo.',
    provides_alcohol_drinks: 0,
    provides_decoration: 0,
    provides_parking_service: 1,
    serves_external_address: 1,
    buffet_id: 4 },

  { name: 'Festa de Halloween',
    description: 'Celebração do Dia das Bruxas com fantasias e decoração temática.',
    minimum_attendees: 20,
    maximum_attendees: 150,
    duration: 100,
    menu: 'Petiscos assustadores e drinques especiais.',
    provides_alcohol_drinks: 1,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 5 },

  { name: 'Encontro Familiar',
    description: 'Reunião de familiares para confraternização.',
    minimum_attendees: 10,
    maximum_attendees: 100,
    duration: 60,
    menu: 'Churrasco, saladas e sobremesas.',
    provides_alcohol_drinks: 1,
    provides_decoration: 0,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 1 },

  { name: 'Feira de Negócios',
    description: 'Evento para promover produtos e serviços de empresas.',
    minimum_attendees: 100,
    maximum_attendees: 1000,
    duration: 160,
    menu: 'Coffee breaks e almoços.',
    provides_alcohol_drinks: 0,
    provides_decoration: 0,
    provides_parking_service: 1,
    serves_external_address: 1,
    buffet_id: 2 },

  { name: 'Festa da Empresa',
    description: 'Celebração de conquistas e metas alcançadas.',
    minimum_attendees: 50,
    maximum_attendees: 500,
    duration: 120,
    menu: 'Jantar completo e bebidas variadas.',
    provides_alcohol_drinks: 1,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 3 },

  { name: 'Retiro Espiritual',
    description: 'Encontro para reflexão e práticas espirituais.',
    minimum_attendees: 20,
    maximum_attendees: 100,
    duration: 60,
    menu: 'Refeições leves e saudáveis.',
    provides_alcohol_drinks: 0,
    provides_decoration: 0,
    provides_parking_service: 1,
    serves_external_address: 1,
    buffet_id: 4 },

  { name: 'Festa de Carnaval',
    description: 'Celebração do Carnaval com música e dança.',
    minimum_attendees: 30,
    maximum_attendees: 200,
    duration: 100,
    menu: 'Petiscos típicos de Carnaval e bebidas refrescantes.',
    provides_alcohol_drinks: 1,
    provides_decoration: 1,
    provides_parking_service: 1,
    serves_external_address: 0,
    buffet_id: 5 }]

payment_options = [
  { name: 'Dinheiro',
    installment_limit: 1,
    buffet_id: 1 },

  { name: 'Cartão de Crédito',
    installment_limit: 12,
    buffet_id: 2 },

  { name: 'Cartão de Débito',
    installment_limit: 1,
    buffet_id: 3 },

  { name: 'Transferência Bancária',
    installment_limit: 1,
    buffet_id: 4 },

  { name: 'PIX',
    installment_limit: 1,
    buffet_id: 5 },

  { name: 'Boleto Bancário',
    installment_limit: 1,
    buffet_id: 1 },

  { name: 'Cheque',
    installment_limit: 1,
    buffet_id: 2 },

  { name: 'Vale-Alimentação',
    installment_limit: 1,
    buffet_id: 3 },

  { name: 'Vale-Refeição',
    installment_limit: 1,
    buffet_id: 4 },

  { name: 'PayPal',
    installment_limit: 1,
    buffet_id: 5 }]

base_prices = [
  { description: 'Meio de semana',
    minimum: 1000.0,
    additional_per_person: 30.0,
    extra_hour_value: 150.0,
    event_type_id: 1 },

  { description: 'Fim de semana',
    minimum: 1500.0,
    additional_per_person: 40.0,
    extra_hour_value: 200.0,
    event_type_id: 1 },

  { description: 'Valor padrão',
    minimum: 800.0,
    additional_per_person: 20.0,
    extra_hour_value: 120.0,
    event_type_id: 2 },

  { description: 'Meio de semana',
    minimum: 1500.0,
    additional_per_person: 50.0,
    extra_hour_value: 200.0,
    event_type_id: 3 },

  { description: 'Fim de semana',
    minimum: 2000.0,
    additional_per_person: 60.0,
    extra_hour_value: 250.0,
    event_type_id: 3 },

  { description: 'Valor padrão',
    minimum: 600.0,
    additional_per_person: 15.0,
    extra_hour_value: 100.0,
    event_type_id: 4 },

  { description: 'Meio de semana',
    minimum: 1200.0,
    additional_per_person: 40.0,
    extra_hour_value: 180.0,
    event_type_id: 5 },

  { description: 'Fim de semana',
    minimum: 1800.0,
    additional_per_person: 50.0,
    extra_hour_value: 220.0,
    event_type_id: 5 },

  { description: 'Valor padrão',
    minimum: 1000.0,
    additional_per_person: 30.0,
    extra_hour_value: 150.0,
    event_type_id: 6 },

  { description: 'Meio de semana',
    minimum: 1800.0,
    additional_per_person: 50.0,
    extra_hour_value: 220.0,
    event_type_id: 7 },

  { description: 'Fim de semana',
    minimum: 2500.0,
    additional_per_person: 60.0,
    extra_hour_value: 250.0,
    event_type_id: 7 },

  { description: 'Valor padrão',
    minimum: 2000.0,
    additional_per_person: 70.0,
    extra_hour_value: 250.0,
    event_type_id: 8 },

  { description: 'Meio de semana',
    minimum: 2500.0,
    additional_per_person: 80.0,
    extra_hour_value: 280.0,
    event_type_id: 9 },

  { description: 'Fim de semana',
    minimum: 3000.0,
    additional_per_person: 90.0,
    extra_hour_value: 300.0,
    event_type_id: 9 },

  { description: 'Valor padrão',
    minimum: 1200.0,
    additional_per_person: 30.0,
    extra_hour_value: 150.0,
    event_type_id: 10 },

  { description: 'Meio de semana',
    minimum: 2500.0,
    additional_per_person: 100.0,
    extra_hour_value: 300.0,
    event_type_id: 11 },

  { description: 'Fim de semana',
    minimum: 3500.0,
    additional_per_person: 120.0,
    extra_hour_value: 350.0,
    event_type_id: 11 },

  { description: 'Valor padrão',
    minimum: 1000.0,
    additional_per_person: 30.0,
    extra_hour_value: 150.0,
    event_type_id: 12 },

  { description: 'Meio de semana',
    minimum: 2000.0,
    additional_per_person: 80.0,
    extra_hour_value: 250.0,
    event_type_id: 13 },

  { description: 'Fim de semana',
    minimum: 2500.0,
    additional_per_person: 90.0,
    extra_hour_value: 280.0,
    event_type_id: 13 },

  { description: 'Valor padrão',
    minimum: 1500.0,
    additional_per_person: 60.0,
    extra_hour_value: 200.0,
    event_type_id: 14 },

  { description: 'Meio de semana',
    minimum: 1200.0,
    additional_per_person: 40.0,
    extra_hour_value: 180.0,
    event_type_id: 15 },

  { description: 'Fim de semana',
    minimum: 1800.0,
    additional_per_person: 50.0,
    extra_hour_value: 220.0,
    event_type_id: 15 },

  { description: 'Valor padrão',
    minimum: 800.0,
    additional_per_person: 20.0,
    extra_hour_value: 120.0,
    event_type_id: 16 },

  { description: 'Meio de semana',
    minimum: 2500.0,
    additional_per_person: 100.0,
    extra_hour_value: 300.0,
    event_type_id: 17 },

  { description: 'Fim de semana',
    minimum: 3500.0,
    additional_per_person: 120.0,
    extra_hour_value: 350.0,
    event_type_id: 17 },

  { description: 'Valor padrão',
    minimum: 2000.0,
    additional_per_person: 80.0,
    extra_hour_value: 250.0,
    event_type_id: 18 },

  { description: 'Meio de semana',
    minimum: 600.0,
    additional_per_person: 15.0,
    extra_hour_value: 100.0,
    event_type_id: 19 },

  { description: 'Fim de semana',
    minimum: 900.0,
    additional_per_person: 20.0,
    extra_hour_value: 120.0,
    event_type_id: 19 },

  { description: 'Meio de semana',
    minimum: 1200.0,
    additional_per_person: 30.0,
    extra_hour_value: 150.0,
    event_type_id: 20 },

  { description: 'Fim de semana',
    minimum: 1800.0,
    additional_per_person: 40.0,
    extra_hour_value: 180.0,
    event_type_id: 20 }]

buffet_owners.each { |buffet_owner| BuffetOwner.create! buffet_owner }
buffets.each { |buffet| Buffet.find_or_create_by! buffet }
event_types.each { |event_type| EventType.find_or_create_by! event_type }
payment_options.each { |payment_option| PaymentOption.find_or_create_by! payment_option }
base_prices.each { |base_price| BasePrice.find_or_create_by! base_price }

puts 'Seeding completed'